.TH SKI-CLI "1" "June 2016" "skicoin-cli 0.12"
.SH NAME
skicoin-cli \- a remote procedure call client for Skicoin Core. 
.SH SYNOPSIS
skicoin-cli [options] <command> [params] \- Send command to Skicoin Core. 
.TP
skicoin-cli [options] help \- Asks Skicoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the skicoin-cli program. skicoin-cli is an RPC client used to send commands to Skicoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBskicoind\fP, \fBskicoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
